// converting this to MySQL more mysql work
export const posts = [
  {
    id: 500,
    user: 'brock202',
    text: 'Thoughts on RECOVERY preprint: dexamethasone as treatment for COVID-19',
    timeCreated: 1591609880,
    attachmentLink: 'https://www.medrxiv.org/content/10.1101/2020.06.22.20137273v1',
  },
  {
    id: 1000,
    group: { value: 'airdos', label: 'Airdos' },
    children: [1001, 1002, 1003, 1004, 1005],
    user: 'pmaier983',
    text: 'Unsupervised Translation of Programming Languages. Feed a model with Python, C++, and Java source code from GitHub, and it automatically learns to translate between the 3 languages ',
    timeCreated: 1591607880,
    attachmentLink: 'https://arxiv.org/pdf/2006.03511.pdf',
    replies: [
      {
        id: 1001,
        parent: 1000,
        group: { value: 'airdos', label: 'Airdos' },
        user: 'pmaier983',
        text: 'We leverage the same principles that we used to translate low-resource languages (https://arxiv.org/abs/1804.07755), i.e. pretraining, denoising auto-encoding, and back-translation. Although initially designed for natural languages, these methods perfectly apply to programming languages.',
        timeCreated: 1591608020,
      },
      {
        id: 1002,
        parent: 1000,
        group: { value: 'airdos', label: 'Airdos' },
        user: 'pmaier983',
        text: 'The model learns to align functions and objects across libraries (std::unordered_set -> HashSet, printf -> System.out.println, std::vector<int> -> List<Integer>, Files.createDirectories -> os.makedirs), but also language specific patterns (a > b ? a : b -> a if a > b else b)',
        timeCreated: 1591608030,
      },
      {
        id: 1003,
        parent: 1000,
        group: { value: 'airdos', label: 'Airdos' },
        user: 'pmaier983',
        text: 'We create a parallel test set of around 10000 parallel functions, along with associated unit tests. Unlike previous studies that typically evaluate translated functions with BLEU score, we compile and run translations to verify that they successfully pass the unit tests.',
        timeCreated: 1591608050,
      },
      {
        id: 1004,
        parent: 1000,
        group: { value: 'airdos', label: 'Airdos' },
        user: 'pmaier983',
        text: 'The model successfully translates more than 90% of C++ functions from @geeksforgeeks into Java, and around 57% of Python functions into C++. It outperforms commercial solutions at test time, although it requires no parallel data or expert knowledge.',
        timeCreated: 1591608060,
      },
      {
        id: 1005,
        parent: 1000,
        group: { value: 'airdos', label: 'Airdos' },
        user: 'pmaier983',
        text: 'We researchers love pre-training. Our new paper shows that pre-training is unhelpful when we have a lot of labeled data. In contrast, self-training works well even when we have a lot of labeled data. SOTA on PASCAL segmentation & COCO detection. Link: http://arxiv.org/abs/2006.06882 ',
        timeCreated: 1591608080,
      },
    ],
  },
  {
    id: 2000,
    children: [2001, 2002, 2003],
    user: 'brock202',
    text: 'Moving away from negative pairs in self-supervised representation learning: our new SotA method, Bootstrap Your Own Latent (BYOL), narrows the gap between self-supervised & supervised methods simply by predicting previous versions of itself.  conjecture on arithmetic progressions – Unsolved problem in mathematics Translation of Programming Languages. Feed a model with Python, C++, and Java source code from GitHub, and it automatically learns to translate between the 3 languages ',
    timeCreated: 1591609880,
    attachmentLink: 'https://t.co/qyaSXnPQjN?amp=1',
    replies: [
      {
        id: 2001,
        parent: 2000,
        user: 'brock202',
        text: 'Moving away from negative pairs in self-supervised representation learning: our new SotA method, Bootstrap Your Own Latent (BYOL), narrows the gap between self-supervised & supervised methods simply by predicting previous versions of itself. ',
        timeCreated: 1591609900,
      },
      {
        id: 2002,
        parent: 2000,
        user: 'brock202',
        text: 'BYOL (red) outperforms current self-supervised methods (grey) for all tested ResNet architectures & downstream tasks. Our best model (ResNet-200 2x) beats the previous SotA by +3.1 points (79.6% top-1 accuracy, linear evaluation on ImageNet) while using 30% fewer parameters.',
        timeCreated: 1591609920,
      },
      {
        id: 2003,
        parent: 2000,
        user: 'brock202',
        text: 'Furthermore, BYOL reliably performs within 2.5 points of its supervised counterparts for all tested ResNet architectures (ImageNet linear evaluation) & has similar or better transfer performance (classification, object detection) than models pre-trained using ImageNet labels.',
        timeCreated: 1591609920,
      },
    ],
  },
  {
    id: 3000,
    user: 'brock202',
    children: [3001, 3002],
    text: 'Erdős conjecture on arithmetic progressions – Unsolved problem in mathematics Translation of Programming Languages. Feed a model with Python, C++, and Java source code from GitHub, and it automatically learns to translate between the 3 languages ',
    timeCreated: 1591610,
    replies: [
      {
        id: 3001,
        parent: 3000,
        children: [3101, 3201],
        user: 'brock202',
        text: 'If A is a large set of positive integers, meaning that the sum of reciprocals of the numbers in A diverges to ∞, the conjecture on arithmetic progressions – Unsolved problem in mathematics Translation of Programming Languages. Feed a model with Python, C++, and Java source code from GitHub, and it automatically learns to translate between the 3 languages ',
        timeCreated: 1591610050,
        replies: [
          {
            id: 3101,
            parent: 3001,
            user: 'brock202',
            text: 'The special case when A is the set of prime numbers was proved by Ben Green and Terence Tao in 2004 A is a large set of positive integers, meaning that the sum of reciprocals of the numbers in A diverges to ∞, the conjecture on arithmetic progressions – Unsolved problem in mathematics Translation of Programming Languages. Feed a model with Python, C++, and Java source code from GitHub, and it automatically learns to translate between the 3 languages ',
            timeCreated: 1591610080,
          },
          {
            id: 3201,
            parent: 3001,
            user: 'pmaier983',
            text: 'Erdos is amazing!',
            timeCreated: 1591610100,
          },
        ],
      },
      {
        id: 3002,
        parent: 3000,
        user: 'pmaier983',
        text: 'Very Cool!!',
        timeCreated: 1591610100,
      },
    ],
  },
  {
    id: 4000,
    user: 'brock202',
    children: [4001, 4002, 4003, 4004, 4005],
    text: 'An exciting result on arXiv this morning. Thomas Bloom and Olof Sisask have proved the first non-trivial case of a very famous conjecture of Erdös.',
    timeCreated: 1591610,
    replies: [
      {
        id: 4001,
        parent: 4000,
        user: 'brock202',
        text: 'Their result shows that if A is a set of integers such that the sum of the reciprocals of its elements is infinite, then it contains an arithmetic progression of length 3.',
        timeCreated: 1591609900,
      },
      {
        id: 4002,
        parent: 4000,
        user: 'brock202',
        text: 'Another consequence is a new proof of a result of Ben Green: a subset of the primes that is relatively dense must contain a 3AP as well.',
        timeCreated: 1591609900,
      },
      {
        id: 4003,
        parent: 4000,
        user: 'brock202',
        text: 'The approach is to combine ideas from previous progress on Roth’s theorem with ideas of Bateman and Katz on the cap-set problem in order to “complete the square”.',
        timeCreated: 1591609900,
      },
      {
        id: 4004,
        parent: 4000,
        user: 'brock202',
        text: 'The idea of trying to do it like that has been around for a long time, but it has been formidably difficult to get it to work. ',
        timeCreated: 1591609900,
      },
      {
        id: 4005,
        parent: 4000,
        user: 'brock202',
        text: 'There will definitely be a Quanta article about this result! ',
        timeCreated: 1591609900,
      },
    ],
  },
  {
    id: 5000,
    children: [5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008],
    user: 'brock202',
    text: 'Thrilled to see this article finally in print! (first draft was in 2013). The paper proposes a simple framework for learning preferences from choices when choices are subject to a framing effect. Heres a short summary:',
    timeCreated: 1591609880,
    attachmentLink: 'https://pbs.twimg.com/media/EbdIo2YXkAE1bwW?format=png&name=900x900',
    replies: [
      {
        id: 5001,
        parent: 5000,
        user: 'brock202',
        text: 'Economists classically use revealed preferences to infer preferences from choices – if 70% of people select x over y, then 70% of people prefer x to y. But what if choices vary by some seemingly arbitrary factor (a “frame”)?',
        timeCreated: 1591609900,
      },
      {
        id: 5002,
        parent: 5000,
        user: 'brock202',
        text: 'For example, suppose more people choose x when x is the default. Then the fraction of people choosing x might not reveal preferences, resulting in policy controversies. If you don’t know what people prefer, how should you nudge them?',
        timeCreated: 1591609900,
      },
      {
        id: 5003,
        parent: 5000,
        user: 'brock202',
        text: 'In this paper, we adopt a potential outcome framework and analyze this as a statistical problem. For this to work, we need some choices to reveal preferences, so we assume choices reflect preferences 𝘶𝘯𝘭𝘦𝘴𝘴 𝘵𝘩𝘦𝘺 𝘷𝘢𝘳𝘺 𝘣𝘺 𝘧𝘳𝘢𝘮𝘦.',
        timeCreated: 1591609900,
      },
      {
        id: 5004,
        parent: 5000,
        user: 'brock202',
        text: 'If frames push everyone in the same direction, we can identify the distribution of preferences of these “consistent choosers” – the people whose preferences don’t vary by frame. Very easy to apply:',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbdKHXQXgAEnIbm?format=png&name=900x900',
      },
      {
        id: 5005,
        parent: 5000,
        user: 'brock202',
        text: 'Once we know the consistent choosers’ preferences, estimating full population preferences becomes a 𝘴𝘦𝘭𝘦𝘤𝘵𝘪𝘰𝘯 𝘱𝘳𝘰𝘣𝘭𝘦𝘮: we must account for non-random selection into the consistent group. Fortunately, economists think about selection problems all the time!',
        timeCreated: 1591609900,
      },
      {
        id: 5006,
        parent: 5000,
        user: 'brock202',
        text: 'So we adapt classic empirical methods for addressing selection (matching, instruments) to our revealed preference problem. Which methods work well depends on the underlying model of behavior, just like in classical selection models.',
        timeCreated: 1591609900,
      },
      {
        id: 5007,
        parent: 5000,
        user: 'brock202',
        text: 'We illustrate the approach with automatic pension plan enrollment. Consistent employees prefer 401(k) enrollment at higher rates than inconsistent ones. This matters a lot because auto enrollment only affects enrollment for inconsistent employees:',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbdKr1tWoAI73qK?format=png&name=900x900',
      },
      {
        id: 5008,
        parent: 5000,
        user: 'brock202',
        text: 'Specifically, young, low-income workers appear very sensitive to defaults and less likely to prefer enrollment. They also leave the firm quickly, which helps explain why many prefer not to participate. Many of these workers are probably better off without auto-enrollment.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbdK03DWAAYBOgR?format=png&name=900x900',
      },
    ],
  },
  {
    id: 6000,
    children: [6001, 6002, 6003, 6004],
    user: 'brock202',
    text: 'Stochastic Softmax Tricks: We generalize the Gumbel-Softmax, and introduce new tricks for backpropping through all kinds of random discrete objects: spanning trees, subset selection, & more ',
    timeCreated: 1591609880,
    attachmentLink: 'https://t.co/1VvM1BC9Nr?amp=1',
    replies: [
      {
        id: 6001,
        parent: 6000,
        user: 'brock202',
        text: 'The idea: view the Gumbel-Softmax as the solution of a random convex program over the simplex, a Gumbel linear term plus an entropy regularizer. The generalization: stoch. softmax tricks are convex programs over polytopes with random linear terms & strongly convex regularizers.',
        timeCreated: 1591609900,
      },
      {
        id: 6002,
        parent: 6000,
        user: 'brock202',
        text: 'We tested SSTs in deep latent variable models on data with latent combinatorial structure. We found that SSTs can be used to improve performance & recover more structure. E.g., in our toy experiment, training with a spanning tree SST helps the model recover the true tree exactly.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/Eao-tlGXgAEgkik?format=jpg&name=medium',
      },
      {
        id: 6003,
        parent: 6000,
        user: 'brock202',
        text: 'This framework includes previous work (e.g., Gumbel-Sinkhorn) with lots left to explore!',
        timeCreated: 1591609900,
        attachmentLink: 'https://t.co/Vzbjqtpu5b?amp=1',
      },
      {
        id: 6004,
        parent: 6000,
        user: 'brock202',
        text: 'This is cool and related, but we have different goals (generalize Gumbel-Softmax vs. softmax) and techniques (e.g., marginals vs random smoothing).',
        timeCreated: 1591609900,
        attachmentLink: 'https://t.co/YA010uRHdH?amp=1',
      },
    ],
  },
  {
    id: 7000,
    children: [7001, 7002, 7003],
    user: 'brock202',
    text: 'We researchers love pre-training. Our new paper shows that pre-training is unhelpful when we have a lot of labeled data. In contrast, self-training works well even when we have a lot of labeled data. SOTA on PASCAL segmentation & COCO detection. Link: http://arxiv.org/abs/2006.06882 ',
    timeCreated: 1591609880,
    replies: [
      {
        id: 7001,
        parent: 7000,
        user: 'brock202',
        text: 'This work continues our self-training efforts: Noisy Student Training (SOTA on ImageNet): http://arxiv.org/abs/1911.04252 Noisy Student Training for Speech (SOTA on LibriSpeech): http://arxiv.org/abs/2005.09629 Conclusion? Good results on big datasets need self-training (w/ Noisy Student) :)  ',
        timeCreated: 1591609900,
      },
      {
        id: 7002,
        parent: 7000,
        user: 'brock202',
        text: 'In the paper, we evaluate two “pre-training” methods: supervised and self-supervised. Both do not transfer well',
        timeCreated: 1591609900,
      },
      {
        id: 7003,
        parent: 7000,
        user: 'brock202',
        text: `Here's how we use self-training (w/ Noisy Student) in our work: 
        1) Train a model on COCO
2) Infer labels on ImageNet images
3) Train a new model on the combined set with noise added
4) Optional: Iterate the process`,
        timeCreated: 1591609900,
      },
    ],
  },
  {
    id: 8000,
    user: 'brock202',
    text: 'Last week, a press released provided initial and promising results from a large scale trial of the corticosteroid dexamethasone in hospitalized COVID patients. Today the authors released a full report: https://www.medrxiv.org/content/10.1101/2020.06.22.20137273v1.full.pdf',
    timeCreated: 1591609880,
    replies: [
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'As a reminder, dexamethasone was just one arm of the trial. The primary outcome measure was 28-day mortality. I\'m pleased to see that the subgroup analysis reported, namely effect of dexamethasone according to level of respiratory support, was pre-specified.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLgrVqUEAE56Rq?format=png&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'The randomization ended up with an age imbalance which was corrected. Though the correction was not part of the pre-registration, this seems entirely reasonable to me.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLh7ikUwAE7oE6?format=jpg&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'I do not have the expertise in trial design to comment on the decision to stop enrollment. That said, this seems appropriate and I do not see red flags.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLi8oPU0AEr2SJ?format=png&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'In the press release I was surprised the survival difference between ventilators (40%/29% with/without dexamethasone), supplemental oxygen (25%/22%), and neither (13%/17%) was pretty narrow. Here\'s a possible clue: ventilated patients were 10 years younger. I don\'t know why.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLlf0AU0AAz6M8?format=png&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'Secondary measures: Dexamethasone also showed small but significant benefits on time to discharge and probability of avoiding mechanical ventilation. These are overall differences; I do not believe these secondary measures are broken down by breathing support.',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLmhlcVAAAJUQN?format=png&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'For me the take-home is that there are no big surprises relative to what we learned from the press release. The trial gives a strong indication that dexamethasone is beneficial in hospitalized patients requiring respiratory support (O2 or vent).',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLpVa_UMAEawhS?format=jpg&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'As noted in the press release, patients not on respiratory support fared *worse* when treated with dexamethasone. The difference is not statistically significant, but concerning. "There was no benefit (and the possibility of harm) among',
        timeCreated: 1591609900,
        attachmentLink: 'https://pbs.twimg.com/media/EbLpbLLU8AAlf9D?format=jpg&name=medium',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'As I noted before, the trial showed that dexamethasone helps the very ill. It\'s not for mild illness. Taking it won\'t prevent you from getting COVID. Nor, if you have COVID, will it prevent you from being hospitalized.',
        timeCreated: 1591609900,
        attachmentLink: '',
      },
      {
        id: 8001,
        parent: 7000,
        user: 'brock202',
        text: 'Finally, https://twitter.com/EricMeyerowitz  has a more detailed analysis of the paper in this thread that makes for good reading, particularly if you\'ve read the paper and want a deeper dive.',
        timeCreated: 1591609900,
        attachmentLink: '',
      },
    ],
  },
]
