export const posts = [
  {classification:' Group postA2', 
  postType:' Publicizing research', 
  text: 'Our latest pre-print, on the use of saliva as a diagnostic sample for testing [link]', 
},
{classification:' Public & Group', 
postType:' Pre peer-review', 
text: 'Sharing my lab partner\'s initial findings for discussion, in advance of her submission to Nature', 
},
{classification:' Public thread', 
postType:' Discussion topic', 
text: 'I decided to read all relevant Coronavirus preprints. Here\'s what I\'ve found:', 
},
{classification:' Group thread', 
postType:' Pre peer-review', 
text: 'The recent paper by J. Doe [link] predicts these features which are not holding up. Here\'s where I think they go wrong:', 
},
{classification:' Public post', 
postType:' Publicizing research', 
text: 'Just published in Nature [link]. Fundamental cytoskeletal insight here: Length-dependent disassembly maintains four different flagellar lengths in Giardia', 
},
{classification:' Public comment', 
postType:' Pre peer-review', 
text: 'I suggest you re-run the PCR used in section 2, as in my most recent paper [link]', 
},
{classification:' Public post', 
postType:' Discussion topic', 
text: 'Current CB actions don\'t relax budget constraint of the govt intertemporally. Public finance fundamentals did not change. CB just made borrowing easy', 
},
{classification:' Public thread', 
postType:' Pre peer-review', 
text: 'The BCG paper has been released on medRxiv The paper is now under review by Cell. Here are the key takeaways:', 
},
{classification:' Group post', 
postType:' Discussion topic', 
text: 'Based on the J. Doe lab preprint, I think we need to tweak our protocol', 
},
{classification:' Public comment', 
postType:' Discussion topic', 
text: 'Are you planning on sharing cleaned data for this?', 
},
{classification:' Public & Group p', 
postType:' Conference awaren', 
text: 'My poster presentation at ECTRIMS from today [link]! Great to have all the molecular-bio team at U of A dial-in to support. ', 
},
{classification:' Public & Group p', 
postType:' Conference awaren', 
text: 'Latest white paper from Novartis [link], on Ofatumumab\'s impact on the patient experience (full presentation this afternoon at AAN virtual)', 
},
{classification:' Group post', 
postType:' Conference awaren', 
text: 'Please join Merck at their Overcoming Monoclonal Antibody Administration Challenges Workshop this afternoon at 330pm (ET) for a discussion on strategies industry players are taking to commercialize mAbs [link]',
},
{classification:' Public & Group p', 
postType:' Conference awaren', 
text: 'Latest oncology data released at BioEurope by Bluebird Bio, take a peek [photo]', 
},
{classification:' Private Thread', 
postType:' Pre peer-review', 
text: 'The protocal on step 4b of this manuscript needs to be repeated to show proof of effectiveness', 
},
{classification:' Public post', 
postType:' Publicizing research', 
text: 'Product X has officially been approved by the FDA for use in infants'} 
]